export const mockProducts = [
  {
    id: "1",
    name: "Remera Oversized Negra",
    description: "Remera oversize en algodon premium con corte holgado. Diseno minimalista perfecto para el dia a dia.",
    price: 8500,
    category: "Remeras",
    image_url: "/remera-negra-oversized.jpg",
    images: ["/remera-negra-oversized.jpg", "/remera-negra-oversized-back.jpg", "/remera-negra-oversized-detail.jpg"],
    stock: 50,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Blanco", "Gris"],
    featured: true,
    created_at: "2025-01-01",
  },
  {
    id: "2",
    name: "Jogger Cargo Verde Oliva",
    description: "Pantalon jogger con bolsillos cargo. Tejido tecnico resistente y comodo para uso urbano.",
    price: 12000,
    category: "Pantalones",
    image_url: "/pantalon-cargo-verde-oliva.jpg",
    images: [
      "/pantalon-cargo-verde-oliva.jpg",
      "/pantalon-cargo-verde-oliva-side.jpg",
      "/pantalon-cargo-verde-oliva-detail.jpg",
    ],
    stock: 30,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Verde Oliva", "Negro", "Beige"],
    featured: true,
    created_at: "2025-01-02",
  },
  {
    id: "3",
    name: "Sneakers Minimalistas",
    description: "Zapatillas urbanas de diseno minimalista. Suela de goma premium y upper de cuero sintetico.",
    price: 15000,
    category: "Calzado",
    image_url: "/zapatillas-blancas-minimalistas.jpg",
    images: [
      "/zapatillas-blancas-minimalistas.jpg",
      "/zapatillas-blancas-minimalistas-side.jpg",
      "/zapatillas-blancas-minimalistas-sole.jpg",
    ],
    stock: 25,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Blanco", "Negro", "Crema"],
    featured: true,
    created_at: "2025-01-03",
  },
  {
    id: "4",
    name: "Gorra Estructurada",
    description: "Gorra de 6 paneles con logo bordado. Ajuste posterior con hebilla metalica.",
    price: 4500,
    category: "Accesorios",
    image_url: "/gorra-negra-minimalista.jpg",
    images: ["/gorra-negra-minimalista.jpg", "/gorra-negra-minimalista-side.jpg", "/gorra-negra-minimalista-top.jpg"],
    stock: 40,
    sizes: ["Unico"],
    colors: ["Negro", "Blanco", "Verde"],
    featured: true,
    created_at: "2025-01-04",
  },
  {
    id: "5",
    name: "Hoodie Premium",
    description: "Buzo con capucha en algodon brushed. Interior afelpado extra suave y cordones planos.",
    price: 11000,
    category: "Remeras",
    image_url: "/hoodie-gris-premium.jpg",
    images: ["/hoodie-gris-premium.jpg", "/hoodie-gris-premium-back.jpg", "/hoodie-gris-premium-detail.jpg"],
    stock: 35,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gris", "Negro", "Crema"],
    featured: true,
    created_at: "2025-01-05",
  },
  {
    id: "6",
    name: "Chino Slim Fit",
    description: "Pantalon chino de corte slim con cintura media. Tejido stretch para maxima comodidad.",
    price: 10500,
    category: "Pantalones",
    image_url: "/pantalon-chino-beige.jpg",
    images: ["/pantalon-chino-beige.jpg", "/pantalon-chino-beige-side.jpg", "/pantalon-chino-beige-detail.jpg"],
    stock: 28,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Beige", "Azul Marino", "Negro"],
    featured: true,
    created_at: "2025-01-06",
  },
  {
    id: "7",
    name: "Campera Bomber Negra",
    description: "Campera bomber clasica con cierre frontal y bolsillos laterales. Interior forrado para mayor abrigo.",
    price: 18500,
    category: "Abrigos",
    image_url: "/black-bomber-jacket-front-view.jpg",
    images: [
      "/black-bomber-jacket-front-view.jpg",
      "/black-bomber-jacket-back.png",
      "/black-bomber-jacket-detail-zipper.jpg",
    ],
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Verde Militar", "Azul Marino"],
    featured: false,
    created_at: "2025-01-07",
  },
  {
    id: "8",
    name: "Remera Basica Blanca",
    description: "Remera basica de algodon 100% con cuello redondo. Corte regular ideal para uso diario.",
    price: 5500,
    category: "Remeras",
    image_url: "/white-basic-t-shirt-front.jpg",
    images: ["/white-basic-t-shirt-front.jpg", "/white-basic-t-shirt-back.jpg", "/white-basic-t-shirt-side-view.jpg"],
    stock: 100,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blanco", "Negro", "Gris"],
    featured: false,
    created_at: "2025-01-08",
  },
  {
    id: "9",
    name: "Short Deportivo",
    description: "Short deportivo con cintura elastizada y cordon ajustable. Tela liviana y transpirable.",
    price: 7000,
    category: "Pantalones",
    image_url: "/black-sport-shorts-front.jpg",
    images: ["/black-sport-shorts-front.jpg", "/black-sport-shorts-back.jpg", "/black-sport-shorts-side-detail.jpg"],
    stock: 45,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Gris", "Azul"],
    featured: false,
    created_at: "2025-01-09",
  },
  {
    id: "10",
    name: "Buzo Cuello Redondo",
    description: "Buzo de algodon frisado con cuello redondo. Diseno minimalista y versatil.",
    price: 9500,
    category: "Remeras",
    image_url: "/grey-crewneck-sweatshirt-front.jpg",
    images: [
      "/grey-crewneck-sweatshirt-front.jpg",
      "/grey-crewneck-sweatshirt-back.jpg",
      "/grey-crewneck-sweatshirt-detail.jpg",
    ],
    stock: 38,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gris", "Negro", "Beige"],
    featured: false,
    created_at: "2025-01-10",
  },
  {
    id: "11",
    name: "Mochila Urban",
    description:
      "Mochila urbana con compartimento para laptop de 15 pulgadas. Multiples bolsillos y tirantes acolchados.",
    price: 13500,
    category: "Accesorios",
    image_url: "/black-urban-backpack-front.jpg",
    images: [
      "/black-urban-backpack-front.jpg",
      "/black-urban-backpack-back-straps.jpg",
      "/black-urban-backpack-open-compartments.jpg",
    ],
    stock: 22,
    sizes: ["Unico"],
    colors: ["Negro", "Gris", "Verde Militar"],
    featured: false,
    created_at: "2025-01-11",
  },
  {
    id: "12",
    name: "Cinturon de Cuero",
    description: "Cinturon de cuero genuino con hebilla metalica. Acabado premium y costura reforzada.",
    price: 6500,
    category: "Accesorios",
    image_url: "/brown-leather-belt-coiled.jpg",
    images: ["/brown-leather-belt-coiled.jpg", "/brown-leather-belt-buckle.jpg", "/brown-leather-belt-texture.jpg"],
    stock: 50,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Marron", "Negro"],
    featured: false,
    created_at: "2025-01-12",
  },
]
