export const mockProducts = [
  {
    id: "1",
    name: "Remera Oversized Negra",
    description: "Remera oversize en algodón premium con corte holgado. Diseño minimalista perfecto para el día a día.",
    price: 8500,
    category: "Remeras",
    image_url: "/remera-negra-oversized.jpg",
    stock: 50,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Blanco", "Gris"],
    featured: true,
    created_at: "2025-01-01",
  },
  {
    id: "2",
    name: "Jogger Cargo Verde Oliva",
    description: "Pantalón jogger con bolsillos cargo. Tejido técnico resistente y cómodo para uso urbano.",
    price: 12000,
    category: "Pantalones",
    image_url: "/pantalon-cargo-verde-oliva.jpg",
    stock: 30,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Verde Oliva", "Negro", "Beige"],
    featured: true,
    created_at: "2025-01-02",
  },
  {
    id: "3",
    name: "Sneakers Minimalistas",
    description: "Zapatillas urbanas de diseño minimalista. Suela de goma premium y upper de cuero sintético.",
    price: 15000,
    category: "Calzado",
    image_url: "/zapatillas-blancas-minimalistas.jpg",
    stock: 25,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Blanco", "Negro", "Crema"],
    featured: true,
    created_at: "2025-01-03",
  },
  {
    id: "4",
    name: "Gorra Estructurada",
    description: "Gorra de 6 paneles con logo bordado. Ajuste posterior con hebilla metálica.",
    price: 4500,
    category: "Accesorios",
    image_url: "/gorra-negra-minimalista.jpg",
    stock: 40,
    sizes: ["Único"],
    colors: ["Negro", "Blanco", "Verde"],
    featured: false,
    created_at: "2025-01-04",
  },
  {
    id: "5",
    name: "Hoodie Premium",
    description: "Buzo con capucha en algodón brushed. Interior afelpado extra suave y cordones planos.",
    price: 11000,
    category: "Remeras",
    image_url: "/hoodie-gris-premium.jpg",
    stock: 35,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gris", "Negro", "Crema"],
    featured: true,
    created_at: "2025-01-05",
  },
  {
    id: "6",
    name: "Chino Slim Fit",
    description: "Pantalón chino de corte slim con cintura media. Tejido stretch para máxima comodidad.",
    price: 10500,
    category: "Pantalones",
    image_url: "/pantalon-chino-beige.jpg",
    stock: 28,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Beige", "Azul Marino", "Negro"],
    featured: false,
    created_at: "2025-01-06",
  },
  {
    id: "7",
    name: "Bomber Jacket Urban",
    description: "Campera bomber reversible con bolsillos laterales. Cierre frontal con cremallera YKK.",
    price: 18500,
    category: "Remeras",
    image_url: "/black-bomber-jacket-on-mannequin-streetwear.jpg",
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Verde Militar", "Azul Marino"],
    featured: true,
    created_at: "2025-01-07",
  },
  {
    id: "8",
    name: "Mochila Técnica",
    description: "Mochila urbana con compartimento para laptop 15'. Material impermeable y acolchado ergonómico.",
    price: 9500,
    category: "Accesorios",
    image_url: "/black-technical-backpack-urban-style.jpg",
    stock: 45,
    sizes: ["Único"],
    colors: ["Negro", "Gris", "Camuflado"],
    featured: true,
    created_at: "2025-01-08",
  },
  {
    id: "9",
    name: "Botas Chelsea",
    description: "Botas chelsea de cuero premium con suela de goma antideslizante. Diseño clásico reinventado.",
    price: 22000,
    category: "Calzado",
    image_url: "/black-chelsea-boots-leather-minimal.jpg",
    stock: 18,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Negro", "Marrón", "Tan"],
    featured: true,
    created_at: "2025-01-09",
  },
]
